### ISSUE TITLE
randomByte needs quick change for instance mode

### ISSUE THREAD

**Issue by samheckle** [ffd8/p5.glitch#9]
just need to update `newData[bytePos] = this.parseByte(random(255));` to `newData[bytePos] = this.parseByte(this.p5.random(255));` in [p5.glitch.js on 281](https://github.com/ffd8/p5.glitch/blob/master/p5.glitch.js#L281). 

i updated and tested locally and it works :) was throwing an error that random was undefined

**Comment by ffd8** [comment]
@samheckle ahaa - good catch! until now [i was only using](https://github.com/ffd8/GLITCH.ext) `randomBytes()` in instance mode, so didn't hit that bug. 

care to make a PR for this? otherwise, happy to fix

**Comment by ffd8** [comment]
thanks for finding and fixing! 🙏
